#!/usr/bin/env python3
"""Generate the PRISMA 2020 flow diagram as a standalone TikZ file.

Sources of truth:
  data/processed/master_dedup.csv          (identification + dedup totals)
  data/processed/screened.csv              (title/abstract first-pass totals)
  data/processed/fulltext_screening.csv    (uncertain finalisation + full-text decisions)

Output:
  paper/figures/prisma_flow.tex
"""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCREENING = ROOT / "data" / "processed" / "fulltext_screening.csv"
DEDUP = ROOT / "data" / "processed" / "master_dedup.csv"
OUT = ROOT / "paper" / "figures" / "prisma_flow.tex"

# Hard counts already audited and committed in repo / reports
RAW_TOTAL = 1707
RAW_BREAKDOWN = [("IEEE Xplore", 386), ("Web of Science", 50),
                 ("arXiv", 49), ("OpenAlex", 1222)]
DEDUP_REMOVED = 69


def count_rows(path: Path) -> int:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return sum(1 for _ in csv.DictReader(handle))


def fulltext_summary() -> dict[str, int]:
    with SCREENING.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    ta = Counter(r["title_abstract_decision"] for r in rows)
    ftd = Counter(r["final_decision"] for r in rows)
    reason = Counter(r["fulltext_exclusion_reason_code"] for r in rows if r["final_decision"] == "exclude")
    return {
        "candidates": len(rows),
        "ta_include": ta.get("INCLUDE", 0),
        "ta_uncertain": ta.get("UNCERTAIN", 0),
        "ft_include": ftd.get("include", 0),
        "ft_exclude": ftd.get("exclude", 0),
        "reason_no_access": reason.get("no_full_text_access", 0) + reason.get("insufficient_fulltext_access", 0),
        "reason_agent_uncertain": reason.get("agent_uncertain_full_text", 0) + reason.get("borderline_fulltext_case", 0),
        "reason_second_pass": reason.get("second_pass_likely_exclude", 0),
        "reason_protocol": (
            reason.get("no_quantitative_or_reproducible_evidence", 0)
            + reason.get("policy_or_commentary_only", 0)
            + reason.get("not_institutional_setting", 0)
            + reason.get("no_implementation_detail", 0)
        ),
    }


def build_tex(summary: dict[str, int]) -> str:
    unique_records = RAW_TOTAL - DEDUP_REMOVED
    ta_excluded = unique_records - summary["candidates"]
    breakdown = ", ".join(f"{name}: {count}" for name, count in RAW_BREAKDOWN)

    return rf"""% Auto-generated by scripts/generate_prisma_flow.py
% Do not edit by hand. Re-run the script to regenerate.
\begin{{figure*}}[t]
  \centering
  \begin{{tikzpicture}}[
    node distance=8mm and 14mm,
    box/.style={{rectangle, draw, rounded corners=2pt, align=center,
                text width=46mm, minimum height=12mm, font=\footnotesize}},
    excl/.style={{rectangle, draw, rounded corners=2pt, align=left,
                 text width=52mm, minimum height=12mm, font=\footnotesize, fill=gray!7}},
    arrow/.style={{-{{Latex[length=2mm]}}, thick}},
    side/.style={{-{{Latex[length=2mm]}}, thick, dashed}},
  ]
    \node[box] (id) {{\textbf{{Identification}}\\Records identified from databases:\\{RAW_TOTAL} ({breakdown})}};
    \node[box, below=of id] (dedup) {{\textbf{{Records after deduplication}}\\{unique_records} unique records\\({DEDUP_REMOVED} duplicates removed)}};
    \node[box, below=of dedup] (ta) {{\textbf{{Title/Abstract Screening}}\\{unique_records} records screened}};
    \node[excl, right=of ta] (taexcl) {{Excluded at title/abstract:\\\hspace*{{2mm}}{ta_excluded} records\\(out of scope, not blockchain, or no institutional context)}};
    \node[box, below=of ta] (cands) {{\textbf{{Candidate pool}}\\{summary["candidates"]} candidates\\({summary["ta_include"]} clear includes + {summary["ta_uncertain"]} uncertain resolved by agent workflow)}};
    \node[box, below=of cands] (ft) {{\textbf{{Full-Text Screening}}\\Agent full-text review across\\{summary["candidates"]} candidates}};
    \node[excl, right=of ft] (ftexcl) {{Excluded at full-text:\\\hspace*{{2mm}}{summary["ft_exclude"]} records\\\hspace*{{2mm}}--- no open access: {summary["reason_no_access"]}\\\hspace*{{2mm}}--- agent uncertain: {summary["reason_agent_uncertain"]}\\\hspace*{{2mm}}--- triage exclude: {summary["reason_second_pass"]}\\\hspace*{{2mm}}--- protocol fail: {summary["reason_protocol"]}}};
    \node[box, below=of ft, fill=blue!5] (incl) {{\textbf{{Included Studies}}\\{summary["ft_include"]} records carried forward to extraction, quality assessment, and synthesis}};

    \draw[arrow] (id) -- (dedup);
    \draw[arrow] (dedup) -- (ta);
    \draw[arrow] (ta) -- (cands);
    \draw[arrow] (cands) -- (ft);
    \draw[arrow] (ft) -- (incl);
    \draw[side] (ta) -- (taexcl);
    \draw[side] (ft) -- (ftexcl);
  \end{{tikzpicture}}
  \caption{{PRISMA 2020 flow diagram for the blockchain consortium networks systematic review.
  All counts are auto-generated from \texttt{{data/processed/fulltext_screening.csv}} via \texttt{{scripts/generate\_prisma\_flow.py}}.
  The agent-driven uncertain-resolution workflow and the agent full-text review of the first-pass include pool produced the final candidate-to-include funnel reported here.}}
  \label{{fig:prisma-flow}}
\end{{figure*}}
"""


def main() -> None:
    summary = fulltext_summary()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_tex(summary), encoding="utf-8")
    print(f"Wrote {OUT}")
    for key, value in summary.items():
        print(f"  {key}: {value}")


if __name__ == "__main__":
    main()
